### ISSUE TITLE
FTP Password

### ISSUE THREAD

**Issue by edukarma** [BrunoDeBarros/git-deploy-php#43]
Git-deploy cannot handle passwords with special symbols. I had an FTP password like this: 

hU[Irp:Eb}Ov:uC#

It would simply fail to login.

**Comment by Hejprint** [comment]
@edukarma, @BrunoDeBarros 
Is this multi deploys work good with merging?

**Comment by BrunoDeBarros** [comment]
What do you mean about merging?

**Comment by Hejprint** [comment]
Is it deploying only in commits or in merging also?

A deploy is sent when commit is sent. But is it also sent when I will do a merge to the branch that is observed?

For example:
The observed branch is `production`.
I am merging branch `feat/super-functionality` to `production`.
Is there a "deploy trigger" for sth like this?

**Comment by BrunoDeBarros** [comment]
A merge is a commit. After merging, just run `php git-deploy` and it'll deploy everything.
