### ISSUE TITLE
Creates empty files on server

### ISSUE THREAD

**Issue by astroanu** [BrunoDeBarros/git-deploy-php#48]
I ran the script after configuring the ini files. It made empty files on the server. All the files were just empty. Am i doing anything wrong ?

**Comment by BrunoDeBarros** [comment]
Have you been able to look into this?

**Comment by astroanu** [comment]
No not really. The project was on a tight deadline so i had to use conventional FTP uploads :(

**Comment by BrunoDeBarros** [comment]
That's a shame. Have you tried using git-deploy for any other projects since?

**Comment by astroanu** [comment]
unfortunately no. i implemented a gulp task to upload files using vinyl-ftp. which is working fine.
