### ISSUE TITLE
Error: File 'deploy.ini' is not a valid .ini file.

### ISSUE THREAD

**Issue by cfehnel** [BrunoDeBarros/git-deploy-php#53]
When trying to run the script for the first time, I receive this error message.

**Comment by BrunoDeBarros** [comment]
Did you create a deploy.ini file? By default, when you run git-deploy, it looks for a deploy.ini file on the same folder where git-deploy is. Check out the documentation in the README file for details on the options.

**Comment by cfehnel** [comment]
Yes, there is a deploy.ini file in the same folder as git-deploy. I think I figured out the issue, though. It doesn't appear to like the password in the deploy.ini file, perhaps because it has a exclamation point. If I remove the password and type it in the command line everything seems to work properly.

**Comment by BrunoDeBarros** [comment]
Ah the problem is that it should've been wrapped around quotes, it's an issue with parse_ini_file().

**Comment by cfehnel** [comment]
Awesome. That works great. Thanks for the help.
