### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by maskas** [BrunoDeBarros/git-deploy-php#54]
The latest version gives me following error. Is it working for others?

PHP Fatal error:  Class 'Brunodebarros\Gitdeploy\Brunodebarros\Gitdeploy\Git' not found in phar:///var/www/impresspages.org/git-deploy/src/Server.php on line 82
PHP Stack trace:
PHP   1. {main}() /var/www/impresspages.org/git-deploy:0
PHP   2. Brunodebarros\Gitdeploy\Server->deploy() /var/www/impresspages.org/git-deploy:52

**Comment by BrunoDeBarros** [comment]
It's working for me, I use it every day. Are you sure it's the latest version?

**Comment by BrunoDeBarros** [comment]
Oh wait this is for a submodule, which I don't use every day.

**Comment by BrunoDeBarros** [comment]
Have just deployed a fix, can you confirm that it works?

**Comment by maskas** [comment]
Nice. Working fine now. Thanks.
