### ISSUE TITLE
git source?

### ISSUE THREAD

**Issue by lgwapnitsky** [BrunoDeBarros/git-deploy-php#57]
Where do I specify the git source from which I'm pulling?

Thank you

**Comment by BrunoDeBarros** [comment]
You can do this with the --repo option, but you don't have to. Just drop the `git-deploy` file onto your project's repo folder, and run it there. It'll automatically use that.

**Comment by lgwapnitsky** [comment]
OK.  I'm running this on a hosted server which is not my git repo.  Let me
try specifying.  Thanks

**Comment by BrunoDeBarros** [comment]
I think there may be some confusion here - you have your git repo on your computer for development, right? So you drop the `git-deploy` file in there, create a deploy.ini, and then go into your command line, `cd` to that folder and run `git-deploy`, which deploys your changes to your server via FTP or SFTP (whichever you specify in the deploy.ini file).

**Comment by lgwapnitsky** [comment]
ah...now i've got it.  thanks

**Comment by BrunoDeBarros** [comment]
Can I close this issue then? Is everything working for you?

**Comment by lgwapnitsky** [comment]
all good.  thanks!
