### ISSUE TITLE
Error trying to execute

### ISSUE THREAD

**Issue by newelement** [BrunoDeBarros/git-deploy-php#68]
I'm getting this error when trying to run php git-deploy

Uncaught exception 'PharException' with message 'phar "/var/www/html/git-deploy" has a broken signature' in /var/www/html/git-deploy:5

**Comment by BrunoDeBarros** [comment]
You closed this error - did you resolve it?

I'd suggest re-downloading git-deploy. It sounds like something might've gone wrong. I've just cloned the repo and tried running git-deploy, and it worked.

**Comment by newelement** [comment]
Yes. I downloaded it again and it's ok. Thanks
