### ISSUE TITLE
Can i use on the ubuntu machine

### ISSUE THREAD

**Issue by rakeshkumar125** [BrunoDeBarros/git-deploy-php#71]
I was used on the windows machine its working fine. i have seen that in this used a raw file & shows the windows sign. So can i used this on the ubuntu machine.

**Comment by BrunoDeBarros** [comment]
Yep; it works just fine on Unix-based systems - I run it every day on OS X. Don't know what Windows sign you're talking about.

**Comment by rakeshkumar125** [comment]
![windows_sign](https://cloud.githubusercontent.com/assets/5181350/17271475/73751ca4-569a-11e6-85f6-3abeb8838284.png)
i talk about the sign that shown in screen shot. But thanks from your confirmation. Its working ubuntu

**Comment by BrunoDeBarros** [comment]
The file has no extension at all, that might be why it's depicted as a generic Windows sign on Windows. On other platforms it'd be something else. I'm glad it's working for you; I'll close this issue then.
