### ISSUE TITLE
PharException: manifest cannot be larger than 100 MB in phar

### ISSUE THREAD

**Issue by ftechhelp** [BrunoDeBarros/git-deploy-php#82]
We have been using git-deploy to deploy to our production server and absolutely love it! However, we have a few commits that have changed thousands of files to be pushed over to our production server, but every time we try and use git-deploy, we get the following error:

[03-Jan-2018 08:49:29 America/New_York] PHP Fatal error:  Uncaught PharException: manifest cannot be larger than 100 MB in phar "C:\inetpub\wwwroot\MRS_MAIN\git-deploy" in C:\inetpub\wwwroot\MRS_MAIN\git-deploy:16
Stack trace:
#0 C:\inetpub\wwwroot\MRS_MAIN\git-deploy(16): Phar::mapPhar('git-deploy')
#1 {main}
  thrown in C:\inetpub\wwwroot\MRS_MAIN\git-deploy on line 16

Is there a way to fix/bypass that? We have tried everything that we know of.

Thanks.

**Comment by BrunoDeBarros** [comment]
I’ll have to look at it. I’m not sure why the “manifest” is an issue. You haven’t changed git-deploy itself, right?

- Bruno

**Comment by ftechhelp** [comment]
I had but also removed the changes. I re-copied git-deploy to my repository and it works now. Sorry for wasting your time!
